name: Release
on:
  push:
    branches:
      - 'release/**'

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # For the moment we use my personal version of `get-version-action` until this PR https://github.com/battila7/get-version-action/pull/4 was merged
      - id: get_version
        uses:  underq/get-version-action@master

      # See: https://www.mojohaus.org/versions-maven-plugin/examples/set.html#
      - run: mvn versions:set versions:commit -DnewVersion="${{ steps.get_version.outputs.version-without-v }}"

      - name: Commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: "Release ${{ steps.get_version.outputs.version-without-v }}"
          add: 'pom.xml'

      - name: Create Release Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          pr_title: "Release ${{ steps.get_version.outputs.version-without-v }}"

      - name: Create Backport Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: dev
          pr_title: "Release ${{ steps.get_version.outputs.version-without-v }} backport"
