name: Release
on:
  push:
    branches:
      - 'release/**'

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: get_version
        uses: battila7/get-version-action@v2

      - run: echo ${{ steps.get_version.outputs.version }}

      - run: echo ${{ steps.get_version.outputs.version-without-v }}

      - name: Create Release Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          pr_title: "Release ${{ github.ref }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Backport Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: dev
          pr_title: "Release ${{ github.ref }} backport"
          github_token: ${{ secrets.GITHUB_TOKEN }}
