name: Release
on:
  push:
    branches:
      - 'release/**'

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          pr_title: "Release branch ${{ github.ref }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
